<?php

namespace App\Http\Controllers\Voyager;

use TCG\Voyager\Http\Controllers\VoyagerController as BaseVoyagerController;
use DB;

class VoyagerController extends BaseVoyagerController
{
    public function index()
    {
//        return parent::index(); // TODO: Change the autogenerated stub
        return view('vendor/voyager/index');

    }
}
