

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <link rel="stylesheet" type="text/css" href="style.css"/>
</head>
<body>
@foreach($atestado as $key => $value)
<img style="position:absolute;top:3.86in;left:0.35in;width:8.13in;height:0.21in" src="{{asset('images/atestado/ci_1.png')}}" />
<img style="position:absolute;top:5.51in;left:0.35in;width:8.13in;height:0.20in" src="{{asset('images/atestado/ci_2.png')}}" />
<img style="position:absolute;top:11.06in;left:1.56in;width:2.62in;height:0.00in" src="{{asset('images/atestado/ci_3.png')}}" />
<img style="position:absolute;top:11.06in;left:4.97in;width:2.62in;height:0.00in" src="{{asset('images/atestado/ci_4.png')}}" />
<img style="position:absolute;top:12.18in;left:0.44in;width:8.15in;height:0.00in" src="{{asset('images/atestado/ci_5.png')}}" />
<img style="position:absolute;top:1.33in;left:0.56in;width:8.16in;height:0.00in" src="{{asset('images/atestado/ci_6.png')}}" />
<img style="position:absolute;top:9.81in;left:2.92in;width:5.68in;height:0.00in" src="{{asset('images/atestado/ci_7.png')}}" />
<img style="position:absolute;top:11.80in;left:0.65in;width:8.02in;height:0.14in" src="{{asset('images/atestado/ci_8.png')}}" />
<div style="position:absolute;top:11.80in;left:1.00in;width:7.34in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:DejaVu Sans;color:#000000">Responsável Técnico </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:DejaVu Sans;color:#000000">- Médico(a) do Trabalho: Dr(a). ROSANE REIS PONTES E SILVA - CRM: 33643/SP - RQE: 69375/SP</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:DejaVu Sans;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.86in;left:0.35in;width:8.13in;height:0.21in" src="{{asset('images/atestado/ci_9.png')}}" />
<img style="position:absolute;top:5.51in;left:0.35in;width:8.13in;height:0.20in" src="{{asset('images/atestado/ci_10.png')}}" />
<div style="position:absolute;top:0.52in;left:2.27in;width:6.06in;line-height:0.28in;"><span style="font-style:normal;font-weight:bold;font-size:13pt;font-family:Liberation Sans;color:#000000">SSO - ASSESSORIA EM SEGURANÇA E SAÚDE OCUPACIONAL</span><span style="font-style:normal;font-weight:bold;font-size:13pt;font-family:Liberation Sans;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.98in;left:2.00in;width:4.48in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Serif;color:#7f7f7f">Rua Sete de Abril, Nº 59 - Andar 8 - República - São Paulo/SP - CEP: 01043-000</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Serif;color:#7f7f7f"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.93in;left:6.79in;width:1.43in;line-height:0.19in;">
    <span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Atend. Nº:</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN>
    <DIV style="position:relative; left:0.07in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Emissão: </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Liberation Serif;color:#000000">       /        /        </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></DIV>
</div>
<div style="position:absolute;top:1.34in;left:0.45in;width:7.04in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Serif;color:#000000">Em cumprimento ao Capítulo V da CLT Lei 6.514/77 - artigo 168 § 1º e 3º e Portarias Nºs 3.214/78, 3.164/2, 24/94 e 8/96 NR-7</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Serif;color:#000000">do Ministério do Trabalho e Emprego foi emitido o:</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.71in;left:1.38in;width:6.31in;line-height:0.28in;"><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Liberation Serif;color:#6e6e6e">ATESTADO DE SAÚDE OCUPACIONAL (ASO) - DEMISSIONAL</span><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Liberation Serif;color:#6e6e6e"> </span><br/></SPAN></div>
<img style="position:absolute;top:1.96in;left:0.35in;width:8.14in;height:7.58in" src="{{asset('images/atestado/ci_11.png')}}" />
<div style="position:absolute;top:1.99in;left:0.51in;width:5.56in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000;display: flex;">Empresa</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> {{$value->nome_fantasia}} </span><br/></SPAN></div>
<div style="position:absolute;top:1.99in;left:6.69in;width:1.38in;line-height:0.19in;">
    <DIV style="position:relative; left:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000; display: flex">CNPJ</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> {{$value->cnpj}} </span><br/></SPAN></DIV>
    <span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Liberation Serif;color:#000000">.           .        /            -</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN>
</div>
<div style="position:absolute;top:2.36in;left:0.51in;width:0.59in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Endereço</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.73in;left:0.51in;width:0.75in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Funcionário</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.73in;left:6.90in;width:1.17in;line-height:0.19in;">
    <span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">CPF</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN>
    <DIV style="position:relative; left:0.09in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Liberation Serif;color:#000000">   .           .          -</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></DIV>
</div>
<div style="position:absolute;top:3.10in;left:0.52in;width:0.24in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">RG</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.10in;left:2.23in;width:0.72in;line-height:0.19in;">
    <span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Nascimento</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN>
    <DIV style="position:relative; left:0.09in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Liberation Serif;color:#000000"> /       /</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></DIV>
</div>
<div style="position:absolute;top:3.10in;left:3.14in;width:0.91in;line-height:0.18in;">
    <span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Idade</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN>
    <DIV style="position:relative; left:0.09in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Liberation Serif;color:#000000">   a      m</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Liberation Serif;color:#000000"> </span><br/></DIV>
    <DIV style="position:relative; left:0.51in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Cargo</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></DIV>
</div>
<div style="position:absolute;top:3.10in;left:4.05in;width:0.31in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Sexo</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.47in;left:0.51in;width:1.35in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Ambiente de Trabalho</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.90in;left:0.50in;width:4.81in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Foi clinicamente examinado(a), estando exposto(a) aos seguintes fatores de riscos :</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.54in;left:0.51in;width:4.06in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Liberation Serif;color:#000000">Sendo submetido(a) aos seguintes procedimentos diagnósticos:</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.73in;left:0.54in;width:0.21in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000">Cod</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.73in;left:0.88in;width:1.21in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000">Procedimentos Realizados</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.73in;left:3.22in;width:0.52in;line-height:0.13in;">
    <DIV style="position:relative; left:0.16in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000">Data</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000"> </span><br/></DIV>
    <DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000">Realizada</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></DIV>
    <span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Liberation Serif;color:#000000">       /        /</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN>
</div>
<div style="position:absolute;top:5.73in;left:4.05in;width:0.27in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000">Valid</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000"> </span><br/><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000">ade</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.73in;left:4.63in;width:0.22in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000">Cod</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.73in;left:4.98in;width:1.21in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000">Procedimentos Realizados</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.73in;left:7.28in;width:0.47in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000">Data</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000"> </span><br/><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000">Realizada</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.73in;left:8.08in;width:0.32in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000">Valida</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000"> </span><br/><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000">de</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.61in;left:0.48in;width:1.17in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Sendo Considerado</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.60in;left:2.07in;width:0.32in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Apto</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.60in;left:2.42in;width:0.08in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">(</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.60in;left:2.64in;width:0.08in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">)</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.63in;left:2.81in;width:0.92in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Serif;color:#000000">Função Descrita</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.85in;left:0.48in;width:0.32in;line-height:0.16in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Liberation Serif;color:#000000">Data: </span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:9.96in;left:0.76in;width:0.04in;height:0.01in" src="{{asset('images/atestado/ci_12.png')}}" />
<img style="position:absolute;top:9.96in;left:0.79in;width:0.19in;height:0.01in" src="{{asset('images/atestado/ci_13.png')}}" />
<div style="position:absolute;top:9.85in;left:0.98in;width:0.06in;line-height:0.16in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Liberation Serif;color:#000000">/</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:9.96in;left:0.98in;width:0.04in;height:0.01in" src="{{asset('images/atestado/ci_14.png')}}" />
<img style="position:absolute;top:9.96in;left:1.01in;width:0.19in;height:0.01in" src="{{asset('images/atestado/ci_15.png')}}" />
<div style="position:absolute;top:9.85in;left:1.20in;width:0.06in;line-height:0.16in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Liberation Serif;color:#000000">/</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:9.96in;left:1.20in;width:0.04in;height:0.01in" src="{{asset('images/atestado/ci_16.png')}}" />
<img style="position:absolute;top:9.96in;left:1.23in;width:0.32in;height:0.01in" src="{{asset('images/atestado/ci_17.png')}}" />
<div style="position:absolute;top:9.89in;left:1.97in;width:0.53in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Inapto </span></SPAN><br/></div>
<div style="position:absolute;top:9.89in;left:1.97in;width:0.53in;line-height:0.18in;">
    <DIV style="position:relative; left:0.45in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">(</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></DIV>
</div>
<div style="position:absolute;top:9.89in;left:2.63in;width:0.18in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">)    </span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:10.02in;left:2.78in;width:0.04in;height:0.01in" src="{{asset('images/atestado/ci_18.png')}}" />
<img style="position:absolute;top:10.02in;left:2.81in;width:5.69in;height:0.01in" src="{{asset('images/atestado/ci_19.png')}}" />
<div style="position:absolute;top:10.06in;left:0.55in;width:1.11in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000">Parecer Médico:    </span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:10.19in;left:1.62in;width:0.04in;height:0.01in" src="{{asset('images/atestado/ci_20.png')}}" />
<img style="position:absolute;top:10.19in;left:1.66in;width:6.84in;height:0.01in" src="{{asset('images/atestado/ci_21.png')}}" />
<div style="position:absolute;top:11.26in;left:2.10in;width:1.72in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Liberation Serif;color:#000000">Médico(a) Examinador(a)</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.26in;left:5.18in;width:2.11in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Liberation Serif;color:#000000">Recebi a 2ª Via - Funcionário(a)</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.98in;left:1.18in;width:6.47in;line-height:0.16in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Liberation Serif;color:#000000">Este documento deve ser arquivado no Departamento Médico da Empresa ou do serviço contratado, na ficha do funcionário.</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.33in;left:0.43in;width:5.34in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Serif;color:#000000">Tel.: (11)3772-3194 - (11)3771-3484 - E-mail: atendimento@sso.com.br - Site: www.sso.com.br</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.34in;left:8.26in;width:0.33in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Liberation Serif;color:#000000">Pág. 1</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Liberation Serif;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:0.59in;left:0.49in;width:1.44in;height:0.56in" src="{{asset('images/atestado/ri_1.png')}}" />
<div style="position:absolute;top:9.59in;left:0.47in;"><a name="Sendo_Considerado_Apto_(_)"><span style="font-style:normal;font-weight:normal;font-size:5pt;font-family:Times New Roman;color:#000000">&nbsp</span></a></div>
<div style="position:absolute;top:9.89in;left:1.96in;"><a name="Inapto_(_)"><span style="font-style:normal;font-weight:normal;font-size:5pt;font-family:Times New Roman;color:#000000">&nbsp</span></a></div>
@endforeach
</body>
</html>
